<a href="https://colab.research.google.com/github/SteveGachanja/Spoon-Knife/blob/test-branch/Fundamentals_of_Data_Analysis_using_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# While Loop
---




In [1]:
#indentation is part of the loop.
counter = 0
while counter <= 5:
  print(counter)
  counter = counter +1
print("Hello Steve")

0
1
2
3
4
5
Hello Steve


# For Loop
---




In [2]:
y=range(5)
list(y)

[0, 1, 2, 3, 4]

In [3]:
#indentation is part of the loop.
for x in range(3):
  print("Hello Steve Gachanja", x)

Hello Steve Gachanja 0
Hello Steve Gachanja 1
Hello Steve Gachanja 2


# If Statement Loop
---




In [4]:
# We have imported randn Function , from the Numpy Package
from numpy.random import randn

In [5]:
randn()

0.7834777611822771

In [6]:
# -- -2 --- -1 ---- 0 ----- 1 ----- 2
answer = None  # sets value as if counter = 0
x = randn()
if x > 1:
  answer = "Greater than 1"
elif x >= -1:
  answer = "Between -1 and 1"
else:
  answer = "Less than -1"
print(x)
print(answer)

-0.5228664232802228
Between -1 and 1


#Law of Large Numbers

In [7]:
y = 10000000
counter = 0
for x in randn(y):
  if (x > -1 and x < 1):
    counter = counter +1
counter/y

0.6828329

In [8]:
y = 10
counter = 0
for x in randn(y):
  if (x > -1 and x < 1):
    #print(x)
    counter = counter +1
counter/y

0.4

#Working with Lists and Tuples

In [9]:
#------- Lists ---------
myfirstlist = [3,45,True,"YES"]
read01=list(range(100,115,2))  #A generated list, of 0-115, starting from 100. And spaced evenly using 2. 
#------- Functions ---------
len(read01)     # Len function provides length/number of values
max(read01)     # Max function provides max value
# ------ Slicing -----------
list(range(100,115,2))   #List generator
read01[0]=101       #Overwrite the first value [0] , with 101
read01[-5:-1]       # Slicing values
read01[::-1]        #Reversing values
read01[0:5:2]        # Advanced slicing    

[101, 104, 108]

In [10]:
read01[::1] 

[101, 102, 104, 106, 108, 110, 112, 114]

In [11]:
#TUPLES = An Immutable list . or sequence of values
myfirsttuple = (3,45,True,"YES")
type(myfirsttuple)
myfirsttuple[::]

(3, 45, True, 'YES')

#Arrays and Slicing Arrays

In [12]:
#Packages contain Functions
# Example here, We have imported randn Function , from the Numpy Package
from numpy.random import randn
#Arrays have more methods than Lists , and are useful for matrices and tables and Dataframes

In [13]:
import numpy as np
a = np.array([12,455,63.3,True,"abc",100,50,405.6,"Steve"])
a

array(['12', '455', '63.3', 'True', 'abc', '100', '50', '405.6', 'Steve'],
      dtype='<U32')

In [14]:
a[::2]              # Slicing of Arrays
b = a[8:]           # Creating a Slice Copy of an array
b[0]="Gachanja"     # Reassigning values in arrays
a
c = a.copy()        # Making a FUll Copy of an Array , creating a view of an array
c

array(['12', '455', '63.3', 'True', 'abc', '100', '50', '405.6',
       'Gachanja'], dtype='<U32')

#Working with Arrays and Matrices

In [15]:
import numpy as np
mydata = np.arange(0,20)           #Generating numbers into an array
#MATR1 = np.reshape(mydata, (5,4))  # Note : default is opposite to R, in how it will populate the Matrix
MATR1 = mydata.reshape((5,4))       #Same as Calling a function from within the object # Object Oriented Programming
MATR1                           

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
MATR1[2,:]   # Accessing entire Row [2]
MATR1[2,2]

10

In [17]:
r1 = ["I", "am","happy"]
r2 = ["what", "a", "day"]
r3 = [1,2,3]
newMatrix = np.array([r1, r2, r3])   # Retuens all elements as a "String"
newMatrix

array([['I', 'am', 'happy'],
       ['what', 'a', 'day'],
       ['1', '2', '3']], dtype='<U5')

#Dictionaries

In [18]:
#Dictionary = {"key1":"value1" , "key2":"value2" , "key3":"value3" }
# Acccesing values using their keys
Dictionary = {"key1":"value1" , "key2":True , "key3":3 }
Dictionary["key2"]

True

In [19]:
#Points
KobeBryant_PTS = [2832,2430,2323,2201,1970,2078,1616,2133,83,782]
JoeJohnson_PTS = [1653,1426,1779,1688,1619,1312,1129,1170,1245,1154]
LeBronJames_PTS = [2478,2132,2250,2304,2258,2111,1683,2036,2089,1743]
CarmeloAnthony_PTS = [2122,1881,1978,1504,1943,1970,1245,1920,2112,966]
DwightHoward_PTS = [1292,1443,1695,1624,1503,1784,1113,1296,1297,646]
ChrisBosh_PTS = [1572,1561,1496,1746,1678,1438,1025,1232,1281,928]
ChrisPaul_PTS = [1258,1104,1684,1781,841,1268,1189,1186,1185,1564]
KevinDurant_PTS = [903,903,1624,1871,2472,2161,1850,2280,2593,686]
DerrickRose_PTS = [597,597,597,1361,1619,2026,852,0,159,904]
DwayneWade_PTS = [2040,1397,1254,2386,2045,1941,1082,1463,1028,1331]

#Matrix
Points = np.array([KobeBryant_PTS, JoeJohnson_PTS, LeBronJames_PTS, CarmeloAnthony_PTS, DwightHoward_PTS, ChrisBosh_PTS, ChrisPaul_PTS, KevinDurant_PTS, DerrickRose_PTS, DwayneWade_PTS])             

#Players
Players = ["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh","ChrisPaul","KevinDurant","DerrickRose","DwayneWade"]
Pdict = {"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,"ChrisPaul":6,"KevinDurant":7,"DerrickRose":8,"DwayneWade":9}

#Seasons
Seasons = ["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014"]
Sdict = {"2005":0,"2006":1,"2007":2,"2008":3,"2009":4,"2010":5,"2011":6,"2012":7,"2013":8,"2014":9}



In [20]:
Points[0,:]   # Accessing Kobe's points without a Dictionary
Pdict["KobeBryant"]
Points[Pdict["KobeBryant"]]

array([2832, 2430, 2323, 2201, 1970, 2078, 1616, 2133,   83,  782])

In [21]:
Points[Pdict["KobeBryant"]][Sdict["2006"]]

2430

In [22]:
#Games 
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]
#Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])


In [23]:
Games[8][9]
Games[Pdict["DerrickRose"]][Sdict["2014"]]


51

#Matrix Operations

In [24]:
#Field Goals
KobeBryant_FG = [978,813,775,800,716,740,574,738,31,266]
JoeJohnson_FG = [632,536,647,620,635,514,423,445,462,446]
LeBronJames_FG = [875,772,794,789,768,758,621,765,767,624]
CarmeloAnthony_FG = [756,691,728,535,688,684,441,669,743,358]
DwightHoward_FG = [468,526,583,560,510,619,416,470,473,251]
ChrisBosh_FG = [549,543,507,615,600,524,393,485,492,343]
ChrisPaul_FG = [407,381,630,631,314,430,425,412,406,568]
KevinDurant_FG = [306,306,587,661,794,711,643,731,849,238]
DerrickRose_FG = [208,208,208,574,672,711,302,0,58,338]
DwayneWade_FG = [699,472,439,854,719,692,416,569,415,509]
#Matrix
FieldGoals  = np.array([KobeBryant_FG, JoeJohnson_FG, LeBronJames_FG, CarmeloAnthony_FG, DwightHoward_FG, ChrisBosh_FG, ChrisPaul_FG, KevinDurant_FG, DerrickRose_FG, DwayneWade_FG])

#Games 
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]
#Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])

In [25]:
# To do Matrix Operations , they have to be of the same size dimension
import warnings
warnings.filterwarnings('ignore')
FieldGoalsPerGame=np.matrix.round(FieldGoals / Games , 1)   # Average FieldGoals per Game
FieldGoalsPerGame

array([[12.2, 10.6,  9.5,  9.8,  9.8,  9. ,  9.9,  9.5,  5.2,  7.6],
       [ 7.7,  9.4,  7.9,  7.8,  8.4,  7.1,  7. ,  6.2,  5.8,  5.6],
       [11.1,  9.9, 10.6,  9.7, 10.1,  9.6, 10. , 10.1, 10. ,  9. ],
       [ 9.4, 10.6,  9.5,  8.1, 10. ,  8.9,  8. , 10. ,  9.6,  9. ],
       [ 5.7,  6.4,  7.1,  7.1,  6.2,  7.9,  7.7,  6.2,  6.7,  6.1],
       [ 7.8,  7.9,  7.6,  8. ,  8.6,  6.8,  6.9,  6.6,  6.2,  7.8],
       [ 5.2,  6. ,  7.9,  8.1,  7. ,  5.4,  7.1,  5.9,  6.5,  6.9],
       [ 8.7,  8.7,  7.3,  8.9,  9.7,  9.1,  9.7,  9. , 10.5,  8.8],
       [ 5.2,  5.2,  5.2,  7.1,  8.6,  8.8,  7.7,  nan,  5.8,  6.6],
       [ 9.3,  9.3,  8.6, 10.8,  9.3,  9.1,  8.5,  8.2,  7.7,  8.2]])

In [26]:
FieldGoalsPerGame[Pdict["KobeBryant"]][Sdict["2014"]]

7.6

#Home_Work_Solution - Python Fundamentals

In [27]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [28]:
#Calcultating Profit ( Revenue - Expenses)
profit = list([])
for i in range (0, len(revenue)):
  profit.append(revenue[i]-expenses[i])
profit

[2522.67,
 1911.3900000000003,
 -3707.790000000001,
 -2914.3099999999995,
 -599.9200000000001,
 7265.24,
 8210.550000000001,
 3944.9700000000003,
 3328.3899999999994,
 -2238.6500000000015,
 659.5999999999985,
 11629.54]

In [29]:
#Calculating tax (Profit * 30 %)
tax = [round(i * 0.3, 2) for i in profit]
tax

[756.8,
 573.42,
 -1112.34,
 -874.29,
 -179.98,
 2179.57,
 2463.17,
 1183.49,
 998.52,
 -671.6,
 197.88,
 3488.86]

In [30]:
#Profit after tax, [Profit - 30%Tax]
profit_after_tax = list([])

for i in range (0, len(profit)):
  profit_after_tax.append(profit[i]-tax[i])
profit_after_tax

[1765.8700000000001,
 1337.9700000000003,
 -2595.4500000000007,
 -2040.0199999999995,
 -419.94000000000005,
 5085.67,
 5747.380000000001,
 2761.4800000000005,
 2329.8699999999994,
 -1567.0500000000015,
 461.71999999999855,
 8140.68]

In [31]:
#Margin = Profit_after_tax / Revenue
profit_margin = list([])

for i in range (0, len(profit_after_tax)):
  profit_margin.append(profit_after_tax[i] / revenue[i])

profit_margin = [round(i*100, 2) for i in profit_margin]
profit_margin

[12.12,
 17.59,
 -30.14,
 -22.23,
 -5.21,
 62.74,
 49.99,
 28.28,
 22.61,
 -10.9,
 4.31,
 52.75]

In [32]:
# Profit_after_tax mean
mean_Profit_after_tax = sum(profit_after_tax) / len(profit_after_tax)
mean_Profit_after_tax

1750.6816666666666

In [33]:
good_months = list([])

for i in range(0, len(profit)):
  good_months.append(profit_after_tax[i] > mean_Profit_after_tax)

good_months

[True, False, False, False, False, True, True, True, True, False, False, True]

In [34]:
best_month = list([])

for i in range(0, len(profit)):
  best_month.append(profit_after_tax[i] == max(profit_after_tax))

best_month

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

In [35]:
worst_month = list([])

for i in range(0, len(profit)):
  worst_month.append(profit_after_tax[i] == min(profit_after_tax))

worst_month

[False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [36]:
revenue_1000 = [round(i/1000, 2) for i in revenue]
expenses_1000 = [round(i/1000, 2) for i in expenses]
profit_1000 = [round(i, 2) for i in profit]
profit_after_tax_1000 = [round(i, 2) for i in profit_after_tax]

revenue_1000 = [int(i) for i in revenue_1000]
expenses_1000 = [int(i) for i in expenses_1000]
profit_1000 = [int(i) for i in profit_1000]
profit_after_tax_1000 = [int(i) for i in profit_after_tax_1000]

In [37]:
# Print Results
print("Revenue :" , revenue_1000)
print("Expenses :" , expenses_1000)
print("Profit :" , profit_1000)
print("Profit after Tax :" , profit_after_tax_1000)
print("Profit Margin :" , profit_margin)
print("Good months:" , good_months)
print("Best month:" , best_month)
print("Worst month:" , worst_month)

Revenue : [14, 7, 8, 9, 8, 8, 11, 9, 10, 14, 10, 15]
Expenses : [12, 5, 12, 12, 8, 0, 3, 5, 6, 16, 10, 3]
Profit : [2522, 1911, -3707, -2914, -599, 7265, 8210, 3944, 3328, -2238, 659, 11629]
Profit after Tax : [1765, 1337, -2595, -2040, -419, 5085, 5747, 2761, 2329, -1567, 461, 8140]
Profit Margin : [12.12, 17.59, -30.14, -22.23, -5.21, 62.74, 49.99, 28.28, 22.61, -10.9, 4.31, 52.75]
Good months: [True, False, False, False, False, True, True, True, True, False, False, True]
Best month: [False, False, False, False, False, False, False, False, False, False, False, True]
Worst month: [False, False, True, False, False, False, False, False, False, False, False, False]
